In [1]:
%load_ext lab_black
import pandas as pd
import numpy as np
import drnb as nb

In [2]:
import drnb.io as nbio

irisx, _ = nbio.read_dataxy("iris")

* `n_neighbors=5`
* `algorithm="auto"`: one of `"auto"`, `"ball_tree"`, `"kd_tree"`, `"brute`"
* `metric="minkowski"`: one of the metrics from `sklearn.metrics.pairwise.distance_metrics()`
* `p=2`: parameter for the Minkowski metric, i.e. Euclidean distance by default.
* `metric_params=None` dict of keyword args for the `metric`.
* `n_jobs=None`: number of jobs, `-1` means all processors.
* `leaf_size=30`: parameter when `metric="ball_tree"` or `metric="kd_tree"`

In [3]:
import sklearn.metrics.pairwise

sklearn.metrics.pairwise.distance_metrics().keys()

dict_keys(['cityblock', 'cosine', 'euclidean', 'haversine', 'l2', 'l1', 'manhattan', 'precomputed', 'nan_euclidean'])

In [4]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=15, algorithm="auto", n_jobs=-1).fit(irisx)

(dist, idx) = nn.kneighbors(irisx)

In [5]:
idx

array([[  0,  17,   4, ...,  26,  19,  46],
       [  1,  34,  45, ...,  47,   7,  39],
       [  2,  47,   3, ...,  49,  30,  38],
       ...,
       [147, 110, 111, ..., 103, 123, 141],
       [148, 136, 115, ..., 145, 128, 116],
       [149, 127, 138, ...,  63, 111, 147]])

In [6]:
nn.kneighbors(irisx, return_distance=False)

array([[  0,  17,   4, ...,  26,  19,  46],
       [  1,  34,  45, ...,  47,   7,  39],
       [  2,  47,   3, ...,  49,  30,  38],
       ...,
       [147, 110, 111, ..., 103, 123, 141],
       [148, 136, 115, ..., 145, 128, 116],
       [149, 127, 138, ...,  63, 111, 147]])

In [7]:
import drnb.neighbors as nbnbrs

nbnbrs.sklearn_nbrs(irisx, 15)

(array([[  0,  17,   4, ...,  26,  19,  46],
        [  1,  34,  45, ...,  47,   7,  39],
        [  2,  47,   3, ...,  49,  30,  38],
        ...,
        [147, 110, 111, ..., 103, 123, 141],
        [148, 136, 115, ..., 145, 128, 116],
        [149, 127, 138, ...,  63, 111, 147]]),
 array([[0.        , 0.1       , 0.14142136, ..., 0.31622777, 0.33166248,
         0.36055513],
        [0.        , 0.14142136, 0.14142136, ..., 0.36055513, 0.42426407,
         0.45825757],
        [0.        , 0.14142136, 0.24494897, ..., 0.33166248, 0.33166248,
         0.36055513],
        ...,
        [0.        , 0.2236068 , 0.34641016, ..., 0.5       , 0.50990195,
         0.51961524],
        [0.        , 0.24494897, 0.3       , ..., 0.67082039, 0.69282032,
         0.71414284],
        [0.        , 0.28284271, 0.31622777, ..., 0.60827625, 0.6244998 ,
         0.64031242]]))